apiVersion: v1
kind: Service
metadata:
  name: result-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: result-app
    app: demo-voting-app