apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc1
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: pod1
      labels:
        env: prod
    spec:
      containers:
        - name: nginx1
          image: nginx