apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
  labels:
    env: prod
spec:
  template:
    metadata:
      name: pod1
      labels:
        env: prod
    spec:
      containers:
        - name: nginx1
          image: nginx
  replicas: 3